################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc_ex.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma_ex.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_exti.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash_ex.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_gpio.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c_ex.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr_ex.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc_ex.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc_ex.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_subghz.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim_ex.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart_ex.c \
E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_adc.c 

OBJS += \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_adc.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_adc_ex.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_cortex.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_dma.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_dma_ex.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_exti.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_flash.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_flash_ex.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_gpio.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_i2c.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_i2c_ex.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_pwr.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_pwr_ex.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rcc.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rcc_ex.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rtc.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rtc_ex.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_subghz.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_tim.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_tim_ex.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_uart.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_uart_ex.o \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_ll_adc.o 

C_DEPS += \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_adc.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_adc_ex.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_cortex.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_dma.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_dma_ex.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_exti.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_flash.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_flash_ex.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_gpio.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_i2c.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_i2c_ex.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_pwr.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_pwr_ex.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rcc.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rcc_ex.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rtc.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rtc_ex.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_subghz.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_tim.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_tim_ex.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_uart.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_uart_ex.d \
./Drivers/STM32WLxx_HAL_Driver/stm32wlxx_ll_adc.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_adc.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_adc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_adc_ex.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_adc_ex.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_adc_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_cortex.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_cortex.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_cortex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_dma.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_dma.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_dma_ex.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_dma_ex.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_dma_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_exti.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_exti.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_exti.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_flash.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_flash.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_flash_ex.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_flash_ex.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_flash_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_gpio.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_gpio.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_gpio.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_i2c.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_i2c.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_i2c_ex.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_i2c_ex.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_i2c_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_pwr.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_pwr.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_pwr_ex.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_pwr_ex.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_pwr_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rcc.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rcc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rcc_ex.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rcc_ex.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rcc_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rtc.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rtc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rtc_ex.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_rtc_ex.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_rtc_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_subghz.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_subghz.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_subghz.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_tim.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_tim.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_tim_ex.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_tim_ex.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_tim_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_uart.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_uart.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_uart_ex.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_hal_uart_ex.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_hal_uart_ex.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Drivers/STM32WLxx_HAL_Driver/stm32wlxx_ll_adc.o: E:/Seeed/LoRa\ E5/cube_ide/LoRa-E5-develop-package/Drivers/STM32WLxx_HAL_Driver/Src/stm32wlxx_ll_adc.c Drivers/STM32WLxx_HAL_Driver/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32WLE5xx -DCORE_CM4 -DDEBUG -c -I../../Core/Inc -I../../LoRaWAN/App -I../../LoRaWAN/Target -I../../Peripheral/Inc -I../../../../Drivers/STM32WLxx_HAL_Driver/Inc -I../../../../Drivers/CMSIS/Include -I../../../../Drivers/CMSIS/Device/ST/STM32WLxx/Include -I../../../../Middlewares/Third_Party/LoRaWAN/Crypto -I../../../../Middlewares/Third_Party/LoRaWAN/Mac -I../../../../Middlewares/Third_Party/LoRaWAN/Mac/Region -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler -I../../../../Middlewares/Third_Party/LoRaWAN/LmHandler/Packages -I../../../../Middlewares/Third_Party/LoRaWAN/Utilities -I../../../../Middlewares/Third_Party/SubGHz_Phy -I../../../../Middlewares/Third_Party/SubGHz_Phy/stm32_radio_driver -I../../../../Utilities/lpm/tiny_lpm -I../../../../Utilities/misc -I../../../../Utilities/sequencer -I../../../../Utilities/timer -I../../../../Utilities/trace/adv_trace -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/STM32WLxx_HAL_Driver/stm32wlxx_ll_adc.d" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

